# 🤖 ML Model Comparison

In [55]:
import pandas as pd
import numpy as np

df = pd.read_csv("customer_churn_1000.csv")


print(df.head())
print(df.shape)
print(df.dtypes)

   Customer_ID  Age  Monthly_Charges  Tenure_Months  Support_Calls  \
0        10001   22           102.35             57              4   
1        10002   55           118.07             49              2   
2        10003   49           121.71             67              1   
3        10004   39            77.88             70              0   
4        10005   38            79.63             51              1   

   Satisfaction  Churn  
0             2      0  
1             5      0  
2             1      0  
3             5      0  
4             4      0  
(1000, 7)
Customer_ID          int64
Age                  int64
Monthly_Charges    float64
Tenure_Months        int64
Support_Calls        int64
Satisfaction         int64
Churn                int64
dtype: object


In [56]:
X = df[
    [
        "Age",
        "Monthly_Charges",
        "Tenure_Months",
        "Support_Calls",
        "Satisfaction"
    ]
]

y = df["Churn"]

### Task 1 — Prepare the data

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

### Task 2 — Logistic Regression

In [58]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scale_train = scaler.fit_transform(X_train)
scale_test = scaler.transform(X_test)


from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()

logistic_model.fit(scale_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


### Task 3 — Decision Tree

In [59]:
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(
    random_state=42
)

tree_model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


### Task 4 — Controlled Decision Tree

In [60]:
second_tree_model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

second_tree_model.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,3
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [61]:
logistic_pred = logistic_model.predict(scale_test)
tree_pred = tree_model.predict(X_test)
second_tree_pred = second_tree_model.predict(X_test)

print("Logistic Regression: ", logistic_pred)
print("Decision Tree: ", tree_pred)
print("Decision Tree max_depth=3: ", second_tree_pred)

Logistic Regression:  [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
Decision Tree:  [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 1 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
Decision Tree max_depth=3:  [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 

### Task 6 — Evaluate

In [62]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

logistic_accuracy = accuracy_score(y_test, logistic_pred)
logistic_precision = precision_score(y_test, logistic_pred)
logistic_recall = recall_score(y_test, logistic_pred)
logistic_f1 = f1_score(y_test, logistic_pred)


tree_accuracy = accuracy_score(y_test, tree_pred)
tree_precision = precision_score(y_test, tree_pred)
tree_recall = recall_score(y_test, tree_pred)
tree_f1 = f1_score(y_test, tree_pred)

second_tree_accuracy = accuracy_score(y_test, second_tree_pred)
second_tree_precision = precision_score(y_test, second_tree_pred)
second_tree_recall = recall_score(y_test, second_tree_pred)
second_tree_f1 = f1_score(y_test, second_tree_pred)

### Task 7 — Training vs Testing

In [63]:
logistic_train_pred = logistic_model.predict(scale_train)
logistic_train_accuracy = accuracy_score(y_train, logistic_train_pred)

tree_train_pred = tree_model.predict(X_train)
tree_train_accuracy = accuracy_score(y_train, tree_train_pred)

second_tree_train_pred = second_tree_model.predict(X_train)
second_tree_train_accuracy = accuracy_score(y_train, second_tree_train_pred)

### Task 8 🔥 — Comparison DataFrame

In [64]:
results = pd.DataFrame([
    {
        "Model": "Logistic Regression",
        "Train_Accuracy": logistic_train_accuracy,
        "Test_Accuracy": logistic_accuracy,
        "Precision": logistic_precision,
        "Recall": logistic_recall,
        "F1": logistic_f1
    },
    {
        "Model": "Decision Tree with no-max-depth",
        "Train_Accuracy": tree_train_accuracy,
        "Test_Accuracy": tree_accuracy,
        "Precision": tree_precision,
        "Recall": tree_recall,
        "F1": tree_f1
    },
    {
        "Model": "Decision Tree with max-depth = 3",
        "Train_Accuracy": second_tree_train_accuracy,
        "Test_Accuracy": second_tree_accuracy,
        "Precision": second_tree_precision,
        "Recall": second_tree_recall,
        "F1": second_tree_f1
    }
])

print(results)

                              Model  Train_Accuracy  Test_Accuracy  Precision  \
0               Logistic Regression         0.82000          0.850   0.812500   
1   Decision Tree with no-max-depth         1.00000          0.755   0.395349   
2  Decision Tree with max-depth = 3         0.82875          0.805   0.523810   

   Recall        F1  
0   0.325  0.464286  
1   0.425  0.409639  
2   0.275  0.360656  


### Task 9 🔥 — Confusion Matrix

In [65]:
from sklearn.metrics import confusion_matrix

logistic_confusion_matrix = confusion_matrix(y_test, logistic_pred)
tree_confusion_matrix = confusion_matrix(y_test, tree_pred)
second_tree_confusion_matrix = confusion_matrix(y_test, second_tree_pred)

print("Logistic Regression Confusion Matrix: ")
print(logistic_confusion_matrix)
print()
print("Decision Tree Confusion Matrix: ")
print(tree_confusion_matrix)
print()
print("Decision Tree with max-depth = 3 Confusion Matrix: ")
print(second_tree_confusion_matrix)
print()

Logistic Regression Confusion Matrix: 
[[157   3]
 [ 27  13]]

Decision Tree Confusion Matrix: 
[[134  26]
 [ 23  17]]

Decision Tree with max-depth = 3 Confusion Matrix: 
[[150  10]
 [ 29  11]]



### Task 10 — Prediction Probabilities

In [66]:
probabilites = logistic_model.predict_proba(scale_test)

print(probabilites[:, 1])

[0.14731911 0.18051621 0.5122769  0.20922484 0.07340607 0.10805192
 0.05392176 0.6936403  0.09818274 0.09002201 0.34213242 0.3681779
 0.09023829 0.35585675 0.19169092 0.07746543 0.06065233 0.21956062
 0.03231309 0.26585236 0.2385408  0.12276891 0.04632486 0.50665714
 0.47783273 0.52642259 0.17150025 0.57809895 0.2298513  0.19307884
 0.27762191 0.24132297 0.06748924 0.09290873 0.34042432 0.15667653
 0.39439901 0.13721373 0.028451   0.35540281 0.135715   0.38454085
 0.29221401 0.05454837 0.08853522 0.13538252 0.113171   0.287801
 0.00621027 0.33864548 0.31871282 0.27487253 0.02393777 0.16115933
 0.60554126 0.05631523 0.63186072 0.30409848 0.03553307 0.25509526
 0.11010997 0.01742967 0.44717141 0.04287847 0.04829105 0.20509936
 0.06741463 0.06352578 0.05240001 0.30031554 0.02940332 0.09075851
 0.40443973 0.02755575 0.1252652  0.14783263 0.02445792 0.2204414
 0.26766579 0.22528605 0.0232907  0.34804832 0.02448504 0.03828217
 0.54104934 0.89856261 0.18051529 0.01424885 0.47794981 0.24295421

### Task 11 🔥 — New Customer

In [67]:
new_customer = pd.DataFrame({
    "Age": [32],
    "Monthly_Charges": [85],
    "Tenure_Months": [10],
    "Support_Calls": [4],
    "Satisfaction": [2]
})

new_scaled = scaler.transform(new_customer)

new_logistic_pred = logistic_model.predict(new_scaled)
new_decision_pred = tree_model.predict(new_customer)
new_second_decision_pred = second_tree_model.predict(new_customer)
new_logistic_prob = logistic_model.predict_proba(new_scaled)

print("Logistic : ", new_logistic_pred)
print("Probability of churn:", new_logistic_prob[:, 1])
print("Decision Tree : ", new_decision_pred)
print("Decision Tree with max-depth = 3 : ", new_second_decision_pred)

Logistic :  [1]
Probability of churn: [0.59855803]
Decision Tree :  [0]
Decision Tree with max-depth = 3 :  [0]


### Task 12 — Final Comparison

In [68]:
print(results)

                              Model  Train_Accuracy  Test_Accuracy  Precision  \
0               Logistic Regression         0.82000          0.850   0.812500   
1   Decision Tree with no-max-depth         1.00000          0.755   0.395349   
2  Decision Tree with max-depth = 3         0.82875          0.805   0.523810   

   Recall        F1  
0   0.325  0.464286  
1   0.425  0.409639  
2   0.275  0.360656  
