# Numpy Array Operations

##### Experiment 1 — Array + Scalar

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr + 5)

print(arr)

[15 25 35 45]
[10 20 30 40]


##### Experiment 2 — Subtraction

In [4]:
print(arr - 5)

[ 5 15 25 35]


##### Experiment 3 — Multiplication

In [5]:
arr = np.array([2, 4, 6, 8])

print(arr * 2)

[ 4  8 12 16]


##### Experiment 4 — Division

In [6]:
arr = np.array([10, 20, 30, 40])

print(arr / 10)

[1. 2. 3. 4.]


##### Experiment 5 — Array + Array

In [7]:
arr1 = np.array([10,20,30])

arr2 = np.array([1,2,3])

print(arr1 + arr2)

[11 22 33]


##### Experiment 6 — Array - Array

In [8]:
arr1 = np.array([10,20,30])

arr2 = np.array([1,2,3])

print(arr1 - arr2)

[ 9 18 27]


##### Experiment 7 — Array × Array

In [9]:
arr1 = np.array([2,4,6])

arr2 = np.array([3,5,7])

print(arr1 * arr2)

[ 6 20 42]


##### Experiment 8 — Array ÷ Array

In [10]:
arr1 = np.array([20,30,40])

arr2 = np.array([2,3,4])

print(arr1 / arr2)

[10. 10. 10.]


##### Experiment 9 — Comparison Operations

In [13]:
arr = np.array([10,20,30,40])

print(arr > 20)

print(arr == 20)

print(arr <= 30)

[False False  True  True]
[False  True False False]
[ True  True  True False]


##### Experiment 10 — Practical Example

In [18]:
marks = np.array([45, 78, 90, 33, 65])

print(marks >= 40)

passed_students = marks[marks >= 40]

print(passed_students)

[ True  True  True False  True]
[45 78 90 65]


### 🎯 Mini Assignment

##### Q1

Create:

arr = np.array([5,10,15,20])

Print:

arr + 10

arr - 2

arr * 3

arr / 5

In [19]:
arr = np.array([5, 10, 15, 20])

print(arr + 10)
print(arr - 2)
print(arr * 3)
print(arr / 5)

[15 20 25 30]
[ 3  8 13 18]
[15 30 45 60]
[1. 2. 3. 4.]


##### Q2

Create:

arr1 = np.array([2,4,6])

arr2 = np.array([1,3,5])

Print:

Addition,
Subtraction,
Multiplication,
Division

In [20]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,3,5])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


##### Q3

Create:

marks = np.array([35,42,67,89,28])

Print:

marks >= 40

marks < 50

marks == 67

In [21]:
marks = np.array([35,42,67,89,28])

print(marks>=40)
print(marks<50)
print(marks==67)

[False  True  True  True False]
[ True  True False False  True]
[False False  True False False]
