# NumPy Broadcasting

##### Experiment 1 — Scalar Broadcasting

In [3]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr + 100)

[110 120 130 140]


##### Experiment 2 — Multiplication

In [4]:
arr = np.array([2,4,6,8])

print(arr * 10)

[20 40 60 80]


##### Experiment 3 — 2D Broadcasting

In [5]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix + 10)

[[11 12 13]
 [14 15 16]]


##### Experiment 4 — Row Broadcasting

In [6]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

row = np.array([10,20,30])

print(matrix + row)

[[11 22 33]
 [14 25 36]]


##### Experiment 5 — Column Broadcasting

In [7]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

column = np.array([
    [100],
    [200]
])

print(matrix + column)

[[101 102 103]
 [204 205 206]]


##### Experiment 6 — When Broadcasting Fails

In [9]:

arr1 = np.array([1,2,3])

arr2 = np.array([10,20])
try:
    print(arr1 + arr2)
except ValueError:
    print("Different incompatible shapes")

Different incompatible shapes


## 🎯 Mini Assignment

##### Q1

Create:

arr = np.array([10,20,30,40])

Print:

arr + 50

arr * 5

In [10]:
arr = np.array([10,20,30,40])

print(arr + 50)
print(arr * 5)

[60 70 80 90]
[ 50 100 150 200]


##### Q2

Create:

matrix = np.array([
    [5,10,15],
    [20,25,30]
])

Print:

matrix + 100

In [11]:
matrix = np.array([
    [5,10,15],
    [20,25,30]
])

print(matrix + 100)

[[105 110 115]
 [120 125 130]]


##### Q3

Create:

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

row = np.array([10,20,30])

Print:

matrix + row

In [12]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

row = np.array([10,20,30])

print(matrix + row)

[[11 22 33]
 [14 25 36]]


##### Q4

Create:

matrix = np.array([
    [1,2,3],
    [4,5,6]
])

column = np.array([
    [100],
    [200]
])

Print:

matrix + column

In [13]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

column = np.array([
    [100],
    [200]
])

print(matrix + column)

[[101 102 103]
 [204 205 206]]
