# Universal Functions

##### Experiment 1 — Square Root

In [2]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25])

print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


##### Experiment 2 — Power

In [4]:
arr = np.array([1,2,3,4])

print(np.power(arr, 2))

print(np.power(arr, 3))

[ 1  4  9 16]
[ 1  8 27 64]


##### Experiment 3 — Absolute Value

In [5]:
arr = np.array([-10, 20, -30, 40])

print(np.abs(arr))

[10 20 30 40]


##### Experiment 4 — Round

In [6]:
arr = np.array([3.14159, 2.71828, 1.23456])

print(np.round(arr, 2))

[3.14 2.72 1.23]


##### Experiment 5 — Exponential

In [7]:
arr = np.array([1,2,3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


##### Experiment 6 — Natural Log

In [8]:
arr = np.array([1,2,4,8])

print(np.log(arr))

[0.         0.69314718 1.38629436 2.07944154]


##### Experiment 7 — Maximum & Minimum

In [9]:
arr = np.array([15, 80, 42, 91, 67])

print(np.max(arr))
print(np.min(arr))

91
15


##### Experiment 8 — Sum

In [10]:
arr = np.array([10,20,30,40])

print(np.sum(arr))

100


##### Experiment 9 — Mean (Average)

In [11]:
arr = np.array([80,90,100])

print(np.mean(arr))

90.0


##### Experiment 10 — Combined Example

In [12]:
marks = np.array([78, 85, 92, 66, 88])

print("Highest:", np.max(marks))
print("Lowest :", np.min(marks))
print("Average:", np.mean(marks))
print("Total  :", np.sum(marks))

Highest: 92
Lowest : 66
Average: 81.8
Total  : 409
