# Assignments

##### ⭐ Assignment 1 — Employee Salary Analysis

In [2]:
import numpy as np

salary = np.array([35000, 42000, 50000, 38000, 45000])

print(salary)
print(salary + 2000)
print(np.max(salary))
print(np.min(salary))
print(np.mean(salary))
print(np.sum(salary))

[35000 42000 50000 38000 45000]
[37000 44000 52000 40000 47000]
50000
35000
42000.0
210000


##### ⭐⭐ Assignment 2 — Product Price Update

In [4]:
prices = np.array([
    120,
    250,
    180,
    300,
    150
])

prices = prices * 1.10

print(prices)
print(np.round(prices,2))
print(np.max(prices))
print(np.min(prices))

[132. 275. 198. 330. 165.]
[132. 275. 198. 330. 165.]
330.0
132.0


##### ⭐⭐⭐ Assignment 3 — Student Result Analysis

In [5]:
marks = np.array([
    35,
    82,
    67,
    91,
    48,
    76,
    29
])

print(marks >= 40)
print(marks > 80)
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

[False  True  True  True  True  True False]
[False  True False  True False False False]
61.142857142857146
91
29


##### ⭐⭐⭐⭐ Assignment 4 — Sales Dataset

In [11]:
sales = np.array([
    [120,150,180],
    [200,220,250],
    [300,330,360]
])

sales += 20
sales = sales * 1.05
print(np.max(sales))
print(np.min(sales))
print(np.mean(sales))
print(np.sum(sales))


399.0
147.0
267.1666666666667
2404.5


##### ⭐⭐⭐⭐⭐ Assignment 5 — AI Dataset Preprocessing

In [8]:
dataset = np.array([
    [25,50000],
    [30,70000],
    [22,45000],
    [35,80000],
    [28,65000]
])

age = dataset[:,0]
salary = dataset[:,1]

print(np.mean(age))
print(np.max(salary))
print(np.min(salary))
print(np.sum(salary))
print(age > 25)

28.0
80000
45000
310000
[False  True False  True  True]


##### ⭐⭐⭐⭐⭐⭐ Assignment 6 — Scientific Computation

In [9]:
numbers = np.array([
    4,
    9,
    16,
    25,
    36
])

print(np.sqrt(numbers))
print(np.power(numbers, 3))
print(np.sum(numbers))
print(np.mean(numbers))
print(np.max(numbers))
print(np.min(numbers))

[2. 3. 4. 5. 6.]
[   64   729  4096 15625 46656]
90
18.0
36
4


##### 🌟 Bonus Assignment — Student Performance System

In [10]:
students = np.array([
    [85,90,78],
    [92,88,95],
    [70,75,80],
    [88,82,91],
    [76,85,79]
])


students += 5
print(np.max(students))
print(np.min(students))
print(np.sum(students))
print(np.mean(students))
print(students >= 80)

100
75
1329
88.6
[[ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]]
