# Experiments

##### ⭐ Experiment 1 — Student Marks Bonus

In [5]:
import numpy as np

marks = np.array([78, 85, 92, 66, 88])

print(f"Original Marks:\n{marks}")
print(f"Updated Marks:\n{marks + 5}")

Original Marks:
[78 85 92 66 88]
Updated Marks:
[83 90 97 71 93]


##### ⭐⭐ Experiment 2 — Monthly Expenses

In [6]:
expenses = np.array([
    1200,
    1500,
    1800,
    1000,
    2200
])

print(expenses + 200)
print(expenses - 100)
print(expenses * 2)
print(expenses / 2)

[1400 1700 2000 1200 2400]
[1100 1400 1700  900 2100]
[2400 3000 3600 2000 4400]
[ 600.  750.  900.  500. 1100.]


##### ⭐⭐⭐ Experiment 3 — Company Sales

In [7]:
sales = np.array([
    [120,150,180],
    [200,220,250],
    [300,330,360]
])

print(sales + 50)

bonus = np.array([10,20,30])

print(sales + bonus)

[[170 200 230]
 [250 270 300]
 [350 380 410]]
[[130 170 210]
 [210 240 280]
 [310 350 390]]


##### ⭐⭐⭐⭐ Experiment 4 — Student Grades

In [8]:
marks = np.array([35,42,67,89,28,95])

print(marks >= 40)
print(marks >= 80)
print(marks < 50)

[False  True  True  True False  True]
[False False False  True False  True]
[ True  True False False  True False]


##### ⭐⭐⭐⭐⭐ Experiment 5 — Scientific Calculator

In [9]:
numbers = np.array([1,4,9,16,25])

print(np.sqrt(numbers))
print(np.power(numbers, 2))
print(np.sum(numbers))
print(np.mean(numbers))
print(np.min(numbers))
print(np.max(numbers))

[1. 2. 3. 4. 5.]
[  1  16  81 256 625]
55
11.0
1
25


##### ⭐⭐⭐⭐⭐⭐ Experiment 6 — Temperature Analysis

In [10]:
temperatures = np.array([
    31.6,
    29.8,
    33.2,
    30.4,
    28.9
])

print(np.round(temperatures, 1))
print(np.min(temperatures))
print(np.max(temperatures))
print(np.mean(temperatures))

[31.6 29.8 33.2 30.4 28.9]
28.9
33.2
30.78


##### ⭐⭐⭐⭐⭐⭐⭐ Experiment 7 — Bank Balance

In [11]:
balance = np.array([
    -500,
    1200,
    -300,
    700,
    -100
])

print(np.abs(balance))

[ 500 1200  300  700  100]


#### 🌟 Bonus Experiment — Mini Dataset Analysis

In [12]:
students = np.array([
    [85,90,78],
    [92,88,95],
    [70,75,80],
    [88,82,91]
])

print(students + 5)

print(np.max(students))
print(np.min(students))
print(np.mean(students))
print(np.sum(students))

[[ 90  95  83]
 [ 97  93 100]
 [ 75  80  85]
 [ 93  87  96]]
95
70
84.5
1014
