# Mini Project — AI Student Dataset Analyzer

##### Dataset

In [2]:
import numpy as np

students = np.array([
    [101, 85, 90, 78],
    [102, 92, 88, 95],
    [103, 70, 75, 80],
    [104, 88, 82, 91],
    [105, 76, 85, 79]
])

##### ⭐ Part 1 — Dataset Information

In [3]:
print(students.shape)
print(students.ndim)
print(students.size)
print(students.dtype)

(5, 4)
2
20
int64


##### ⭐⭐ Part 2 — Extract Columns

In [5]:
student_ids = students[:, 0]
math_marks = students[:, 1]
python_marks = students[:, 2]
ml_marks = students[:, 3]

print(student_ids)
print(math_marks)
print(python_marks)
print(ml_marks)

[101 102 103 104 105]
[85 92 70 88 76]
[90 88 75 82 85]
[78 95 80 91 79]


##### ⭐⭐⭐ Part 3 — Add Bonus Marks

In [6]:
updated_students = students.copy()

updated_students[:,1:] += 5

print(updated_students)

[[101  90  95  83]
 [102  97  93 100]
 [103  75  80  85]
 [104  93  87  96]
 [105  81  90  84]]


##### ⭐⭐⭐⭐ Part 4 — Dataset Statistics

In [10]:
print("Math")
print(f"Highest: {np.max(updated_students[:, 1])}")
print(f"Lowest: {np.min(updated_students[:, 1])}")
print(f"Average: {np.mean(updated_students[:, 1])}")
print()
print("Python")
print(f"Highest: {np.max(updated_students[:, 2])}")
print(f"Lowest: {np.min(updated_students[:, 2])}")
print(f"Average: {np.mean(updated_students[:, 2])}")
print()
print("ML")
print(f"Highest: {np.max(updated_students[:, 3])}")
print(f"Lowest: {np.min(updated_students[:, 3])}")
print(f"Average: {np.mean(updated_students[:, 3])}")

Math
Highest: 97
Lowest: 75
Average: 87.2

Python
Highest: 95
Lowest: 80
Average: 89.0

ML
Highest: 100
Lowest: 83
Average: 89.6


##### ⭐⭐⭐⭐⭐ Part 5 — Student Reports

In [11]:
print(f"Student ID :{updated_students[1,0]}")
print(f"Math: {updated_students[1, 1]}")
print(f"Python: {updated_students[1, 2]}")
print(f"ML: {updated_students[1, 3]}")
print()
print(f"Student ID :{updated_students[-1,0]}")
print(f"Math: {updated_students[-1, 1]}")
print(f"Python: {updated_students[-1, 2]}")
print(f"ML: {updated_students[-1, 3]}")

Student ID :102
Math: 97
Python: 93
ML: 100

Student ID :105
Math: 81
Python: 90
ML: 84


##### ⭐⭐⭐⭐⭐⭐ Part 6 — Performance Check

In [13]:
print("Students scoring 90 or more in:")
print("Math")
print(updated_students[:,1] >= 90)
print()
print("Python")
print(updated_students[:,2] >= 90)
print()
print("ML")
print(updated_students[:,3] >= 90)

Students scoring 90 or more in:
Math
[ True  True False  True False]

Python
[ True  True False False  True]

ML
[False  True False  True False]


##### ⭐⭐⭐⭐⭐⭐⭐ Part 7 — Overall Dataset Summary

In [18]:
print(f"Total Student: {updated_students.shape[0]}")
print(f"Total Subject: {updated_students.shape[1]-1}")
print(f"Highest Marks: {np.max(updated_students[:, 1:])}")
print(f"Lowest Marks: {np.min(updated_students[:, 1:])}")
print(f"Average Marks: {np.mean(updated_students[:, 1:])}")


Total Student: 5
Total Subject: 3
Highest Marks: 100
Lowest Marks: 75
Average Marks: 88.6


##### 🌟 Bonus Challenge

In [19]:
bonus = np.array([2,3,5])

print(students[:,1:] + bonus)pp

[[ 87  93  83]
 [ 94  91 100]
 [ 72  78  85]
 [ 90  85  96]
 [ 78  88  84]]
