##### Experiment - 1 - Creating Your First Array

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


##### Experiment 2 — Check the Type

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


##### Experiment 3 — Creating Different Arrays

In [5]:
arr1 = np.array((1, 2, 3, 4))

print(arr1)

[1 2 3 4]


In [6]:
arr2 = np.array([1.2, 3.4, 5.6])

print(arr2)

[1.2 3.4 5.6]


In [7]:
arr3 = np.array(["AI", "ML", "Python"])

print(arr3)

['AI' 'ML' 'Python']


##### Experiment 4 — Array Properties

In [8]:
arr = np.array([10, 20, 30, 40, 50])

print(f"Shape: {arr.shape}")

print(f"N-Dimension: {arr.ndim}")

print(f"Size: {arr.size}")

print(f"Data type: {arr.dtype}")

Shape: (5,)
N-Dimension: 1
Size: 5
Data type: int64


##### Experiment 5 — Two-Dimensional Array

In [10]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [11]:
print(f"Shape: {matrix.shape}")

print(f"N-Dimension: {matrix.ndim}")

print(f"Size: {matrix.size}")

print(f"Data type: {matrix.dtype}")

Shape: (2, 3)
N-Dimension: 2
Size: 6
Data type: int64


##### Experiment 6 — Mixed Data Types

In [12]:
arr = np.array([1, 2.3, 4])

print(arr)

print(arr.dtype)

[1.  2.3 4. ]
float64
