##### NumPy Indexing & Slicing


In [1]:
import numpy as np

##### Experiment 1 — Basic Indexing

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

print(arr[2])

print(arr[4])

10
30
50


##### Experiment 2 — Negative Indexing

In [3]:
print(arr[-1])

print(arr[-2])

50
40


##### Experiment 3 — Slicing

In [5]:
arr = np.array([10,20,30,40,50,60])

print(arr[0:3])

print(arr[2:])

print(arr[:4])

print(arr[:])

print(arr[::2])


[10 20 30]
[30 40 50 60]
[10 20 30 40]
[10 20 30 40 50 60]
[10 30 50]


##### Experiment 4 — 2D Indexing

In [7]:
matrix = np.array([
    [10,20,30],
    [40,50,60]
])

print(matrix[0,1])

print(matrix[1,2])

20
60


##### Experiment 5 — Entire Row

In [8]:
print(matrix[0])

print(matrix[1])

[10 20 30]
[40 50 60]


##### Experiment 6 — Entire Column

In [9]:
print(matrix[:,0])

print(matrix[:,1])

print(matrix[:,2])

[10 40]
[20 50]
[30 60]


##### Experiment 7 — Submatrix

In [10]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[:2, :2])

[[1 2]
 [4 5]]


# Mini Assignment

### Q1

Create:

arr = np.array([5,10,15,20,25,30])

Print:

First element
Last element
Third element

In [11]:
arr = np.array([5,10,15,20,25,30])

print(arr[0])

print(arr[-1])

print(arr[2])

5
30
15


### Q2

Using the same array, print:

First four elements,
Last three elements,
Every second element

In [13]:
print(arr[:4])

print(arr[3:])

print(arr[::2])

[ 5 10 15 20]
[20 25 30]
[ 5 15 25]


### Q3

Create:

matrix = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])

Print:

Element 22
Element 33
Entire second row
Entire first column

In [21]:
matrix = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33]
])

print(matrix[1,1])
print(matrix[2,2])

print(matrix[1, :])
print(matrix[:, 0])

22
33
[21 22 23]
[11 21 31]


### Q4

Using the same matrix, print the top-left 2×2 submatrix.

In [23]:
print(matrix[:2, :2])

[[11 12]
 [21 22]]
