##### ⭐ Assignment 1 — Student Marks

In [3]:
import numpy as np

marks = np.array([92, 85, 78, 96, 88])

In [4]:
print(marks)

print(marks[0])
print(marks[-1])

print(marks[:3])
print(marks[3:])
print(marks[::2])

print(marks.shape)
print(marks.ndim)
print(marks.size)
print(marks.dtype)

[92 85 78 96 88]
92
88
[92 85 78]
[96 88]
[92 78 88]
(5,)
1
5
int64


##### ⭐⭐ Assignment 2 — Monthly Sales

In [5]:
sales = np.array([
    [1200, 1500, 1800],
    [2100, 1900, 2500],
    [3000, 2800, 3200]
])

In [7]:
print(sales)

print(sales[1, :])
print(sales[:, 2])
print(sales[:, 1])
print(sales[2, 1])

print(sales.shape)
print(sales.ndim)
print(sales.size)
print(sales.dtype)

[[1200 1500 1800]
 [2100 1900 2500]
 [3000 2800 3200]]
[2100 1900 2500]
[1800 2500 3200]
[1500 1900 2800]
2800
(3, 3)
2
9
int64


##### ⭐⭐⭐ Assignment 3 — Employee Data

In [8]:
employees = np.array([
    [101, 50000],
    [102, 60000],
    [103, 55000],
    [104, 70000]
])

In [11]:
print(employees[:, 0])
print(employees[:, 1])

print(employees[2, 1])
print(employees[:2, :])
print(employees[-1, :])

[101 102 103 104]
[50000 60000 55000 70000]
55000
[[  101 50000]
 [  102 60000]]
[  104 70000]


##### ⭐⭐⭐⭐ Assignment 4 — Matrix Slicing

In [12]:
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

In [16]:
print(matrix[:2, :2])

print(matrix[-2:, -2:])

print(matrix[:, 1])

print(matrix[2, :])

[[1 2]
 [5 6]]
[[11 12]
 [15 16]]
[ 2  6 10 14]
[ 9 10 11 12]


##### ⭐⭐⭐⭐⭐ Assignment 5 — Mini Dataset Exploration

In [17]:
dataset = np.array([
    [25, 50000],
    [30, 70000],
    [22, 45000],
    [35, 80000],
    [28, 65000]
])

In [24]:
print(dataset[:, 0])
print(dataset[:, 1])

print(dataset[2, 0])
print(dataset[-1, 1])

print(dataset[:3, :])
print(dataset[-2:, :])
print(dataset[: : 2])

[25 30 22 35 28]
[50000 70000 45000 80000 65000]
22
65000
[[   25 50000]
 [   30 70000]
 [   22 45000]]
[[   35 80000]
 [   28 65000]]
[[   25 50000]
 [   22 45000]
 [   28 65000]]


##### 🌟 Bonus Challenge

In [25]:
cube = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

In [26]:
print(cube.shape)
print(cube.ndim)
print(cube.size)
print(cube.dtype)

(2, 2, 2)
3
8
int64
