# Mini Project - Student Performance Dataset

In [2]:
import numpy as np

students = np.array([
    [101, 85, 90, 78],
    [102, 92, 88, 95],
    [103, 70, 75, 80],
    [104, 88, 82, 91],
    [105, 76, 85, 79]
])

### Part 1 — Dataset Information ⭐

In [3]:
print(students.shape)
print(students.ndim)
print(students.size)
print(students.dtype)

(5, 4)
2
20
int64


### Part 2 — Extract Individual Columns ⭐⭐

In [4]:
student_ids = np.array([students[:,0]])
math_marks = np.array([students[:,1]])
python_marks = np.array([students[:,2]])
ml_marks = np.array([students[:,3]])

In [7]:
print(f"Student IDs:\n{student_ids}\n")
print(f"Math:\n{math_marks}\n")
print(f"Python:\n{python_marks}\n")
print(f"ML:\n{ml_marks}\n")

Student IDs:
[[101 102 103 104 105]]

Math:
[[85 92 70 88 76]]

Python:
[[90 88 75 82 85]]

ML:
[[78 95 80 91 79]]



### Part 3 — Individual Student Reports ⭐⭐

In [9]:
print(f"Student 102:\n{students[1, :]}\n")
print(f"Student 105:\n{students[-1, :]}\n")

Student 102:
[102  92  88  95]

Student 105:
[105  76  85  79]



### Part 4 — Subject Selection ⭐⭐⭐

In [11]:
only_marks = students[:,1:]

print(only_marks)

[[[85 90 78]
  [92 88 95]
  [70 75 80]
  [88 82 91]
  [76 85 79]]]


### Part 5 — Dataset Slicing ⭐⭐⭐

In [17]:
print("First three students")
print(students[:3, :])

print("Last two students")
print(students[-2:, :])

print("Every alternate student")
print(students[::2])

First three students
[[101  85  90  78]
 [102  92  88  95]
 [103  70  75  80]]
Last two students
[[104  88  82  91]
 [105  76  85  79]]
Every alternate student
[[101  85  90  78]
 [103  70  75  80]
 [105  76  85  79]]


### Part 6 — Advanced Slicing ⭐⭐⭐⭐

In [20]:
print("Math and Python marks only for the first three students")
print(students[:3, 1:3])

print("Python and ML marks for the last two students")
print(students[-2:, 2:])

Math and Python marks only for the first three students
[[85 90]
 [92 88]
 [70 75]]
Python and ML marks for the last two students
[[82 91]
 [85 79]]


### Part 7 — Find Specific Values ⭐⭐⭐⭐

In [24]:
print("Math marks of Student 104")
print(students[-2, 1])

print("Python marks of Student 103")
print(students[2, 2])

print("ML marks of Student 102")
print(students[1, 3])

print("ID of the final student")
print(students[-1, 0])

Math marks of Student 104
88
Python marks of Student 103
75
ML marks of Student 102
95
ID of the final student
105


### 🌟 Bonus — Build a Smaller Dataset

In [28]:
bonus = students[1:-1, [0,2,3]]

print(bonus)

[[102  88  95]
 [103  75  80]
 [104  82  91]]
