### Q1

A NumPy array of your favorite 5 numbers.

Print:

array
shape
ndim
size
dtype

In [7]:
import numpy as np

arr = np.array([7, 9, 17, 21, 30])

print(arr)

[ 7  9 17 21 30]


In [2]:
print(arr.shape)

print(arr.ndim)

print(arr.size)

print(arr.dtype)

(5,)
1
5
int64


### Q2

A 2×3 matrix of student marks.

Example:

90 85 88
75 80 92

Print:

matrix
shape
ndim
size
dtype


In [3]:
matrix = np.array([
    [90, 85, 88],
    [75, 80, 92]
])

print(matrix)

[[90 85 88]
 [75 80 92]]


In [4]:
print(matrix.shape)

print(matrix.ndim)

print(matrix.size)

print(matrix.dtype)

(2, 3)
2
6
int64


### Q3

Create an array from this tuple:

(10, 20, 30, 40)

Print its type.

In [5]:
arr = np.array((10, 20, 30, 40))

print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


### Q4

Create:

np.array([5, 7.5, 9])

Predict:

What will the array look like?
What will dtype be?

Then run it and verify your prediction.

In [6]:
arr = np.array([5, 7.5, 9])

print(arr)
print(arr.dtype)

[5.  7.5 9. ]
float64
