# Attention — The Core Idea

In [11]:
import numpy as np 

In [12]:
X = np.array([
    [1.0, 0.0],
    [0.9, 0.1],
    [0.0, 1.0]
])

Q = X
K = X
V = X

scores = Q @ K.T

print("Scores: ")
print(scores)

Scores: 
[[1.   0.9  0.  ]
 [0.9  0.82 0.1 ]
 [0.   0.1  1.  ]]


In [13]:
print(scores.shape)

(3, 3)


In [14]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

In [15]:
attension_weight = softmax(scores)

print("Attension Weight: ")
print(attension_weight)

print("Rows Sum: ")
print(attension_weight.sum(axis=1))

Attension Weight: 
[[0.44000202 0.39813029 0.1618677 ]
 [0.42150603 0.3890991  0.18939487]
 [0.20732037 0.22912444 0.56355519]]
Rows Sum: 
[1. 1. 1.]


In [16]:
attension_output = attension_weight @ V

print("Attension Output: ")
print(attension_output)

print("Shape: ")
print(attension_output.shape)

Attension Output: 
[[0.79831928 0.20168072]
 [0.77169522 0.22830478]
 [0.41353237 0.58646763]]
Shape: 
(3, 2)


# Practical Task

In [17]:
X = np.array([
    [1.0, 0.0, 1.0],
    [0.9, 0.1, 0.8],
    [0.0, 1.0, 0.2],
    [0.2, 0.8, 0.1]
])

Q = X
K = X
V = X

In [18]:
scores = Q @ K.T

print("Scores: ")
print(scores)

print("Shape: ")
print(scores.shape)

Scores: 
[[2.   1.7  0.2  0.3 ]
 [1.7  1.46 0.26 0.34]
 [0.2  0.26 1.04 0.82]
 [0.3  0.34 0.82 0.69]]
Shape: 
(4, 4)


In [19]:
attension_weight = softmax(scores)

print("Attension Weight: ")
print(attension_weight)

print("Rows Sum: ")
print(attension_weight.sum(axis=1))

Attension Weight: 
[[0.47874363 0.35466201 0.07913579 0.08745857]
 [0.43855487 0.34497948 0.10390582 0.11255983]
 [0.16033011 0.17024437 0.37138338 0.29804214]
 [0.19231438 0.20016288 0.3234781  0.28404464]]
Rows Sum: 
[1. 1. 1. 1.]


In [21]:
output = attension_weight @ V

print("Attension Output: ")
print(output)

print("Shape: ")
print(output.shape)

Attension Output: 
[[0.81543115 0.18456885 0.78704625]
 [0.77154836 0.22845164 0.7465756 ]
 [0.37315847 0.62684153 0.4006065 ]
 [0.4292699  0.5707301  0.44554476]]
Shape: 
(4, 3)


### Experiment

In [22]:
X[2] = [5.0, 5.0, 5.0]

In [23]:
Q = X
K = X
V = X

scores = Q @ K.T

print("Scores: ")
print(scores)

print("Shape: ")
print(scores.shape)

attension_weight = softmax(scores)

print("Attension Weight: ")
print(attension_weight)

print("Rows Sum: ")
print(attension_weight.sum(axis=1))

output = attension_weight @ V

print("Attension Output: ")
print(output)

print("Shape: ")
print(output.shape)

Scores: 
[[ 2.    1.7  10.    0.3 ]
 [ 1.7   1.46  9.    0.34]
 [10.    9.   75.    5.5 ]
 [ 0.3   0.34  5.5   0.69]]
Shape: 
(4, 4)
Attension Weight: 
[[3.35246306e-04 2.48356572e-04 9.99355153e-01 6.12439766e-05]
 [6.74607600e-04 5.30665134e-04 9.98621582e-01 1.73145311e-04]
 [5.90009054e-29 2.17052201e-29 1.00000000e+00 6.55440854e-31]
 [5.41154726e-03 5.63239670e-03 9.80963305e-01 7.99275137e-03]]
Rows Sum: 
[1. 1. 1. 1.]
Attension Output: 
[[4.99734678 4.9968496  4.99731582]
 [4.99429475 4.99329949 4.99422436]
 [5.         5.         5.        ]
 [4.91689578 4.91177396 4.91553326]]
Shape: 
(4, 3)
