# A practical NumPy example

In [2]:
import numpy as np

In [3]:
vocal_size = 6
embedding_dim = 4

embedding_matrix = np.random.randn(
    vocal_size,
    embedding_dim
)

print("Embedding Matrix: ")
print(embedding_matrix)

Embedding Matrix: 
[[-0.93529479 -0.39453031 -0.30770094 -1.02858652]
 [ 0.47859877 -0.5422683   0.75005629  0.46528794]
 [-0.07311994  0.46524316 -0.29908689  0.17945935]
 [-0.25610309 -0.73246304  1.43250055  0.14491591]
 [-1.42057528  1.32798771  0.57243352 -2.06254105]
 [-0.91379085  0.24899493  0.45321956 -0.20444924]]


In [4]:
token_id = 2

token_vector = embedding_matrix[token_id]

print("Token ID: ", token_id)
print("Token Vector: ", token_vector)

Token ID:  2
Token Vector:  [-0.07311994  0.46524316 -0.29908689  0.17945935]


## Multiple tokens

In [5]:
token_ids = np.array([2, 4, 1])

vectors = embedding_matrix[token_ids]

print(vectors)

[[-0.07311994  0.46524316 -0.29908689  0.17945935]
 [-1.42057528  1.32798771  0.57243352 -2.06254105]
 [ 0.47859877 -0.5422683   0.75005629  0.46528794]]


## Practical Task

In [6]:
vocab = {
    "I": 0,
    "love": 1,
    "AI": 2,
    "and": 3,
    "Python": 4
}

embedding_dim = 5

embedding_matrix = np.random.randn(
    len(vocab),
    embedding_dim
)

In [7]:
text = ["I", "love", "AI"]

token_ids = [vocab[token] for token in text]
print(token_ids)

[0, 1, 2]


In [8]:
vectors = embedding_matrix[token_ids]

In [9]:
print("Token IDs:")
print(token_ids)

print("\nEmbedding vectors:")
print(vectors)

print("\nShape:")
print(vectors.shape)

Token IDs:
[0, 1, 2]

Embedding vectors:
[[ 0.28850843 -0.41760258 -0.86776119 -0.83484467 -0.47568852]
 [-0.93623349  1.92030001 -0.44021679 -0.82054663  0.11530018]
 [-0.34648195 -1.47055555 -0.58308488  0.29383291  0.68200924]]

Shape:
(3, 5)


In [10]:
import tiktoken

encoding = tiktoken.get_encoding("cl100k_base")

In [11]:
text = "I love AI"

token_ids = encoding.encode(text)

print("Token IDs: ", token_ids)
print("Number of tokens: ", len(token_ids))

Token IDs:  [40, 3021, 15592]
Number of tokens:  3
