# Practical Task

In [13]:
import numpy as np

In [14]:
X = np.array([
    [1.0, 0.0, 1.0, 0.0],
    [0.9, 0.1, 0.8, 0.2],
    [0.1, 1.0, 0.2, 0.9],
    [0.2, 0.8, 0.1, 1.0]
])

print("X shape: ", X.shape)

X shape:  (4, 4)


In [15]:
d_model = 4
d_k = 3
d_v = 3

W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_v)

In [16]:
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

print("Q shape: ", Q.shape)
print("K shape: ", K.shape)
print("V shape: ", V.shape)

Q shape:  (4, 3)
K shape:  (4, 3)
V shape:  (4, 3)


In [17]:
scores = Q @ K.T

print("Scores Shape: ", scores.shape)

Scores Shape:  (4, 4)


In [18]:
scaled_scores = scores / np.sqrt(d_k)

In [19]:
def softmax(x):
    exp_x = np.exp(
        x - np.max(x, axis=-1, keepdims=True)
    )

    return exp_x / np.sum(
        exp_x,
        axis=-1,
        keepdims=True
    )

In [20]:
attention_weights = softmax(scaled_scores)

print("Attension Weight Shape: ", attention_weights.shape)

Attension Weight Shape:  (4, 4)


In [21]:
output = attention_weights @ V

print("Output Shape: ", output.shape)

Output Shape:  (4, 3)


In [22]:
print(attention_weights.sum(axis=1))

[1. 1. 1. 1.]


## One more Example with mask

In [25]:
import numpy as np


def softmax(x):
    exp_x = np.exp(
        x - np.max(
            x,
            axis=-1,
            keepdims=True
        )
    )

    return exp_x / np.sum(
        exp_x,
        axis=-1,
        keepdims=True
    )


X = np.array([
    [1.0, 0.0, 1.0, 0.0],
    [0.9, 0.1, 0.8, 0.2],
    [0.1, 1.0, 0.2, 0.9],
    [0.2, 0.8, 0.1, 1.0]
])

d_model = 4
d_k = 3
d_v = 3

W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_v)


# Step 1: Create Q, K, V

Q = X @ W_Q
K = X @ W_K
V = X @ W_V


# Step 2: Attention scores

scores = Q @ K.T


# Step 3: Scale

scaled_scores = (
    scores / np.sqrt(d_k)
)


# Step 4: Create causal mask

mask = np.tril(
    np.ones((4, 4))
)


# Step 5: Apply mask

masked_scores = np.where(
    mask == 1,
    scaled_scores,
    -1e9
)


# Step 6: Softmax

attention_weights = softmax(
    masked_scores
)


# Step 7: Weighted values

output = attention_weights @ V


print("Mask:")
print(mask)

print("\nAttention weights:")
print(attention_weights)

print("\nRow sums:")
print(attention_weights.sum(axis=1))

print("\nOutput:")
print(output)

print("\nOutput shape:")
print(output.shape)

Mask:
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]

Attention weights:
[[1.         0.         0.         0.        ]
 [0.47519036 0.52480964 0.         0.        ]
 [0.47089943 0.31570116 0.21339942 0.        ]
 [0.265334   0.20608703 0.3567603  0.17181867]]

Row sums:
[1. 1. 1. 1.]

Output:
[[ 3.84825244  1.04266774 -0.1423013 ]
 [ 3.62467428  0.8006066  -0.19141418]
 [ 3.32762032  0.77694147 -0.04862046]
 [ 2.76030185  0.50234122  0.07137271]]

Output shape:
(4, 3)


## Challenge

In [28]:
def causal_self_attention(X, W_Q, W_K, W_V):
    # Step 1: Create Q, K, V

    Q = X @ W_Q
    K = X @ W_K
    V = X @ W_V


    # Step 2: Attention scores

    scores = Q @ K.T


    # Step 3: Scale

    d_k = K.shape[-1]

    scaled_scores = (
        scores / np.sqrt(d_k)
    )


    # Step 4: Create causal mask

    seq_len = X.shape[0]

    mask = np.tril(
        np.ones((seq_len, seq_len))
    )


    # Step 5: Apply mask

    masked_scores = np.where(
        mask == 1,
        scaled_scores,
        -1e9
    )


    # Step 6: Softmax

    attention_weights = softmax(
        masked_scores
    )


    # Step 7: Weighted values

    output = attention_weights @ V

    # step 8: Return output and attention weights

    return output, attention_weights