# Build Simplified Self-Attention

In [1]:
import numpy as np 

X = np.array([
    [1.0, 0.0, 1.0, 0.0],
    [0.9, 0.1, 0.8, 0.2],
    [0.1, 1.0, 0.2, 0.9],
    [0.2, 0.8, 0.1, 1.0]
])

print("X Shape: ", X.shape)

X Shape:  (4, 4)


In [2]:
d_model = 4
d_k = 3
d_v = 3

W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_v)

In [4]:
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

print("Q shape:", Q.shape)
print("K shape:", K.shape)
print("V shape:", V.shape)

Q shape: (4, 3)
K shape: (4, 3)
V shape: (4, 3)


In [6]:
scores = Q @ K.T

print("Scores shape:", scores.shape)

Scores shape: (4, 4)


In [7]:
scaled_scores = scores / np.sqrt(d_k)

In [8]:
def softmax(x):
    exp_x = np.exp(
        x - np.max(x, axis=-1, keepdims=True)
    )

    return exp_x / np.sum(
        exp_x,
        axis=-1,
        keepdims=True
    )

In [13]:
attention_weights = softmax(scaled_scores)

print("Attention weights:")
print(attention_weights)

Attention weights:
[[0.03288565 0.04439147 0.58541608 0.3373068 ]
 [0.02900737 0.04026347 0.58690256 0.3438266 ]
 [0.00575865 0.01038326 0.65297576 0.33088233]
 [0.00910242 0.01551304 0.62583287 0.34955168]]


In [14]:
print(attention_weights.sum(axis=1))

[1. 1. 1. 1.]


In [16]:
output = attention_weights @ V

print("Output shape:", output.shape)

Output shape: (4, 3)


## Everything Into One Function

In [17]:
def self_attention(X, W_Q, W_K, W_V):
    Q = X @ W_Q
    K = X @ W_K
    V = X @ W_V

    scores = Q @ K.T

    d_k = K.shape[-1]
    scaled_scores = scores / np.sqrt(d_k)

    attention_weights = softmax(scaled_scores)

    output = attention_weights @ V

    return output, attention_weights